### PR TITLE
Use sync.Once as singleton implimentation

### PR DESCRIPTION
**Pull request by orsonwang**
To make singleton creation a more secure one using sync.Once.

### CODE REVIEW

**Comment by mishan** [comment]
:+1: Thank you @orsonwang !

**Comment by mishan** [comment]
I think you're missing this line from var ( ... ):

`	once sync.Once`

**Comment by orsonwang** [comment]
Sorry, have put it back. now it completes.

**Comment by mishan** [comment]
Cool! Thanks :rocket: :ship:

**Pull request merged**
