### PR TITLE
FCM support

### PR DESCRIPTION
**Pull request by dehy**

### CODE REVIEW

**Comment by TysonAndre** [comment]
This PR seems like it should work, but I haven't actually tested it with fcm yet.

Unit tests from gcm should be easy to copy over for fcm.

**Comment by dehy** [comment]
Hallelujah! I'm so sorry about those bad commits...

**Comment by muspelheim** [comment]
@TysonAndre Hi, any info here?

**Comment by TysonAndre** [comment]
The current status of FCM support:

1. I wanted myself or one of the maintainers to verify that pushes could be sent through FCM before merging this.
    I haven't got FCM set up with android studio until just now, and android teams I've worked with in my company are working on other features, and hasn't started testing FCM.
    I'm planning to test that in the near future.
2. There was code duplication in fcm.go and gcm.go, which would lead to the modules diverging in future work. I wasn't sure of a strategy I wanted to use to resolve that.
     I moved most of the common code into an anonymous struct field: https://github.com/uniqush/uniqush-push/pull/148

**Comment by TysonAndre** [comment]
A refactored FCM module based on this PR was merged into master in https://github.com/uniqush/uniqush-push/pull/148

> 1. The current status of FCM support:
> 
> I wanted myself or one of the maintainers to verify that pushes could be sent through FCM before merging this.


I verified pushes could be sent through FCM with the steps mentioned in https://github.com/uniqush/uniqush-push/pull/148#issuecomment-308930427

**Pull request closed without merging**
